// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPhoneAndPassword(arg1:string,arg2:string):Promise<void>;

export function RefreshGachaHistory():Promise<string>;

export function ReloadFrontend():Promise<void>;

export function WindowClose():Promise<void>;

export function WindowMinSize():Promise<void>;

export function WindowToggleMaxSize():Promise<boolean>;
